name: Fetch YouTube Data

on:
  schedule:
    - cron: "0 */1 * * *"   # 1時間ごとに実行
  workflow_dispatch:         # 手動実行も可能

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Convert notebooks to Python
        run: pip install nbconvert
             jupyter nbconvert --to script fetch_popular_videos.ipynb
             jupyter nbconvert --to script fetch_statistics.ipynb
              
      - name: Fetch Popular Videos
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: python fetch_polular_videos.py

      - name: Fetch Statistics for All Known Videos
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: python fetch_statistics.py

      - name: Commit & Push Results
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Auto update trending and stats data" || echo "No changes to commit"
          git push
